title: "積算の哲学 – The Philosophy of Dynamic Integration"
description: "日本の戦後失った読解力を取り戻し、OODAを実践するためのOS"
lang: "ja"
theme: minima

# ★ 追加：SEO/サイトマップ/OGP用
url: "https://sxjrtfs69q-rgb.github.io"
baseurl: "/dynamic-integration-philosophy"
timezone: "Asia/Tokyo"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: pretty

collections:
  modules:
    output: true

defaults:
  - scope: { path: "" }
    values:
      layout: page
      toc: true
      author: "shun watanabe"

# ヘッダーメニューは非表示のまま
header_pages:
  - index.md
  - philosophy/sekisan-no-tetsugaku.md
  - modules/reading/index.md
  - modules/ooda/index.md
  - modules/regeneration/index.md
  - modules/society/index.md
  - modules/inferno/index.md
  - README.md

author: "Shun Watanabe"
email: ""        # 公開しないなら空でOK
logo: "/assets/images/samurai.png"   
twitter_username: ""             # あれば入れる
github_username: "sxjrtfs69q-rgb"
# 末尾に追加
structured_data:
  "@context": "https://schema.org"
  "@type": "CreativeWork"
  "name": "積算の哲学 – The Philosophy of Dynamic Integration"
  "author": "Shun Watanabe"
  "description": "読解力・OODA・自己再生・社会復帰・冥府編を通して、人間のOSを再設計する思想体系。"
  "inLanguage": "ja"
  "keywords": ["哲学", "OODA", "読解力", "人間のOS", "社会構造", "AI倫理"]
  "url": "https://sxjrtfs69q-rgb.github.io/dynamic-integration-philosophy/"

