title: "積算の哲学 – The Philosophy of Dynamic Integration"
description: "日本の戦後失った読解力を取り戻し、OODAを実践するためのOS"
lang: "ja"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
permalink: /posts/:title/
collections:
  modules:
    output: true
defaults:
  - scope: {path: ""}
    values:
      layout: page
      toc: true
      author: "shun watanabe"

header_pages: []
